### PR TITLE
Using context managers for file open/close

### PR DESCRIPTION
**Pull request by ranr01**

### CODE REVIEW

**Comment by gustavla** [comment]
Looks good! If you can amend the PR with a commit that removes the extra whitespace in:

     with  tables.open_file(path, mode='r') as h5file:
         ^^

That would make it perfect! You can see it as additional GitHub practice - otherwise, I'll just accept it as it is an do it myself later. Thanks again for this!

**Comment by ranr01** [comment]
I removed the space and committed the change. Is that enough?

**Comment by gustavla** [comment]
That's all you needed to do, thanks!

**Comment by ranr01** [comment]
Sure. No problem! Thanks for the practice.

**Comment by gustavla** [comment]
This closes #3.

**Pull request merged**
